include:
  - project: 'nds-ifce-maracanau/devops-shared-jobs'
    ref: 'nds-devops'
    file: 'nds-dotnet.yml'

variables:
  #Build
  SELF_CONTAINED_DEPLOY: true
  #Deploy
  SERVICE: 'Senium'
  DEPLOY_PATH: '/var/www/src/Senium/backend'
  OUTPUT_PUBLISH: 'publish'
  PROJECT_BUILD: 'src/Senium.API/Senium.API.csproj'
